[package]
name = "ayjx"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.28"
futures-util = "0.3"
http = "1.4"
url = "2.5"
serde = { version = "1.0", features = ["derive"] }
simd-json = "0.17"
toml = "0.9"
sea-orm = { version = "1.1", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
chrono = "0.4"
araea-wordcloud = "0.1"
jieba-rs = "0.8"
regex = "1.12"
rand = "0.9"
image = "0.25"
base64 = "0.22"
plotters = "0.3"
