[package]
name = "ayjx"
version = "0.1.0"
edition = "2024"

[dependencies]
# 异步运行时与网络框架
tokio = { version = "1", features = ["full"] }
axum = "0.8"
http = "1.4"
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }

# 序列化与反序列化
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
quick-xml = "0.38"

# HTTP客户端与工具
reqwest = { version = "0.12", features = ["json"] }
futures-util = "0.3"
async-trait = "0.1"

# 加密、哈希与编码
hmac = "0.12.1"
sha1 = "0.10.6"
hex = "0.4.3"
uuid = { version = "1.19", features = ["v4", "fast-rng"] }

# 日期时间与工具
chrono = "0.4"
