[package]
name = "ayjx"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
araea-wordcloud = "0.1"
base64 = "0.22"
cdp-html-shot = "0.2"
chrono = "0.4"
font-kit = "0.14"
futures-util = "0.3"
http = "1.4"
image = "0.25"
jieba-rs = "0.8"
md5 = "0.8"
plotters = "0.3"
rand = "0.9"
regex = "1.12"
reqwest = "0.12"
sea-orm = { version = "1.1", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = "0.17"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.28"
toml = "0.9"
url = "2.5"
which = "8.0"
